INSERT INTO breed (name) VALUES ('Akita');
INSERT INTO breed (name) VALUES ('Australian terrier');
INSERT INTO breed (name) VALUES ('basenji');
INSERT INTO breed (name) VALUES ('basset hound');
INSERT INTO breed (name) VALUES ('beagle');
INSERT INTO breed (name) VALUES ('bearded collie');
INSERT INTO breed (name) VALUES ('Bedlington terrier');
INSERT INTO breed (name) VALUES ('Bernese mountain dog');
INSERT INTO breed (name) VALUES ('bloodhound');
INSERT INTO breed (name) VALUES ('border collie');
INSERT INTO breed (name) VALUES ('border terrier');
INSERT INTO breed (name) VALUES ('Boston terrier');
INSERT INTO breed (name) VALUES ('boxer');
INSERT INTO breed (name) VALUES ('bull terrier');
INSERT INTO breed (name) VALUES ('bulldog');
INSERT INTO breed (name) VALUES ('bullmastiff');
INSERT INTO breed (name) VALUES ('Chihuahua');
INSERT INTO breed (name) VALUES ('Chinese shar-pei');
INSERT INTO breed (name) VALUES ('chow chow');
INSERT INTO breed (name) VALUES ('Clumber spaniel');
INSERT INTO breed (name) VALUES ('cocker spaniel');
INSERT INTO breed (name) VALUES ('Doberman pinscher');
INSERT INTO breed (name) VALUES ('English cocker spaniel');
INSERT INTO breed (name) VALUES ('English setter');
INSERT INTO breed (name) VALUES ('English springer spaniel');
INSERT INTO breed (name) VALUES ('English toy spaniel');
INSERT INTO breed (name) VALUES ('Eskimo dog');
INSERT INTO breed (name) VALUES ('Finnish spitz');
INSERT INTO breed (name) VALUES ('fox terrier');
INSERT INTO breed (name) VALUES ('foxhound');
INSERT INTO breed (name) VALUES ('French bulldog');
INSERT INTO breed (name) VALUES ('German shepherd');
INSERT INTO breed (name) VALUES ('German shorthaired pointer');
INSERT INTO breed (name) VALUES ('Golden retriever');
INSERT INTO breed (name) VALUES ('Great Dane');
INSERT INTO breed (name) VALUES ('Greyhound');
INSERT INTO breed (name) VALUES ('Jack Russell terrier');
INSERT INTO breed (name) VALUES ('Labrador retriever');
INSERT INTO breed (name) VALUES ('Lakeland terrier');
INSERT INTO breed (name) VALUES ('Maltese');
INSERT INTO breed (name) VALUES ('Mastiff');
INSERT INTO breed (name) VALUES ('Pointer');
INSERT INTO breed (name) VALUES ('Pomeranian');
INSERT INTO breed (name) VALUES ('Poodle');
INSERT INTO breed (name) VALUES ('Pug');
INSERT INTO breed (name) VALUES ('Rottweiler');
INSERT INTO breed (name) VALUES ('Saint Bernard');
INSERT INTO breed (name) VALUES ('Shetland sheepdo');
INSERT INTO breed (name) VALUES ('Shih tzu');
INSERT INTO breed (name) VALUES ('Siberian husky');
INSERT INTO breed (name) VALUES ('Silky terrier');
INSERT INTO breed (name) VALUES ('Skye terrier');
INSERT INTO breed (name) VALUES ('Weimaraner');
INSERT INTO breed (name) VALUES ('Yorkshire terrier');